---
clients:
  literacy_status:
    member_literate:
      type: select_list
      position: 1
      values: [:no, :yes]
      default_value: "is this member litrate?"
      validations:
        required: false
    husband_litrate:
      type: select_list
      values: [:no, :yes]
      position: 2
      default_value: "is spouse litrate?"
      validations:
        required: false
