---
clients:
  caste_religion_data:
    religion:
      type: select_list
      position: 1
      values: [:hindu, :muslim, :sikh, :jain, buddha, :christian]
      default_value: "Select religion"
      validations:
        required: false
    caste:
      type: select_list
      position: 1
      values: [:sc, :st, :obc, :general]
      default_value: "Select caste"
      validations:
        required: false
